# Generated by Django 2.2.1 on 2019-05-18 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('author', models.CharField(max_length=50, verbose_name='نویسنده')),
                ('price', models.CharField(max_length=50, verbose_name='قیمت')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrow', models.DateField(default=datetime.datetime(2019, 5, 18, 12, 28, 48, 748800, tzinfo=utc))),
                ('time_borrow', models.TimeField(default=datetime.datetime(2019, 5, 18, 12, 28, 48, 748800, tzinfo=utc))),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_date', models.DateField(default=datetime.datetime(2019, 5, 18, 12, 28, 48, 749800, tzinfo=utc))),
                ('count', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('image', models.ImageField(upload_to='products')),
                ('date_made', models.DateField()),
                ('type', models.CharField(choices=[['C', 'CellPhones'], ['T', 'Television'], ['C', 'Computer']], default='C', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nationalCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('product', models.ManyToManyField(through='first_app.Buy', to='first_app.Product')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Customer'),
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Product'),
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50, verbose_name='نام')),
                ('lastName', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('Book', models.ManyToManyField(through='first_app.Book_Borrower', to='first_app.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book_borrower',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Borrower'),
        ),
    ]
