# Generated by Django 2.2.1 on 2019-05-19 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_borrower',
            name='date_borrow',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 13, 2, 19, 361000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book_borrower',
            name='time_borrow',
            field=models.TimeField(default=datetime.datetime(2019, 5, 19, 13, 2, 19, 361000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='buy',
            name='buy_date',
            field=models.DateField(default=datetime.datetime(2019, 5, 19, 13, 2, 19, 363000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[['C', 'CellPhones'], ['T', 'Television'], ['L', 'Laptops']], default='C', max_length=1),
        ),
    ]
